language: node_js
node_js:
  - "10"
  - "12"
  - "13"

before_script:
  - "npx tsc"

script:
  - "npx jest"

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: npm
  api_key: $NPMJS_COM_API_TOCKEN
  email: "samizdam@inbox.ru"
  skip_cleanup: true
  on:
    tags: true
